### ISSUE TITLE
Bug: Hosting a flan-t5 large model with fastapi and ucall, but in this case time required for fastapi and ucall is almost same

### ISSUE THREAD

**Issue by mmk32001** [unum-cloud/ujrpc#108]
### Describe the bug

**Output for fastapi:**
0
{"result":"<pad> there are a big house behind my school,</s>"}
1
{"result":"<pad> there are a big house behind my school,</s>"}
2
{"result":"<pad> there are a big house behind my school,</s>"}
**avg_fast_api:  6.717146476109822**

**Output for ucall:**

0
{'jsonrpc': '2.0', 'id': 13345, 'result': '<pad> there are a big house behind my school,</s>'}
1
{'jsonrpc': '2.0', 'id': 58355, 'result': '<pad> there are a big house behind my school,</s>'}
2
{'jsonrpc': '2.0', 'id': 19701, 'result': '<pad> there are a big house behind my school,</s>'}
**avg_ucall_client:  7.955343882242839**

Ucall should be faster, compared to fastapi

### Steps to reproduce

**START SERVER**
```
# using ucall uring

from ucall.uring import Server
from transformers import T5Tokenizer, T5ForConditionalGeneration

server = Server()

@server
def flan(input_text: str):
    tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-large")
    model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-large")
    input_ids = tokenizer(input_text, return_tensors="pt").input_ids
    outputs = model.generate(input_ids)
    ans = tokenizer.decode(outputs[0])

    return ans

server.run()


# using fast api


from fastapi import FastAPI
from pydantic import BaseModel
from transformers import T5Tokenizer, T5ForConditionalGeneration

class FlanRequest(BaseModel):
    input_text: str

server = FastAPI()

@server.post('/flan')
def sum(reques: FlanRequest ):
    tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-large")
    model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-large")
    input_ids = tokenizer(reques.input_text, return_tensors="pt").input_ids
    outputs = model.generate(input_ids)
    ans = tokenizer.decode(outputs[0])

    return {"result": ans}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app=server, host=".....", port=8000)

```
**FIND AVG TIME**
```
#using ucall

from ucall.client import Client
import time
import requests

myobj = {
           "input_text":"Fix grammar: there are a big house behind my school,",
        }

client = Client()

sum_time=0

for i in range (0,3):
    print(i)
    start = time.time()
    response = client({
        'method': 'flan',
        'params': myobj,
        'jsonrpc': '2.0',
        'id': 100,
    })
    end=time.time()
    print(response.data)
    sum_time += (end-start) 


avg_ucall_client = sum_time/3
print("avg_ucall_client: ",avg_ucall_client)


#using fast api

sum_time=0
for i in range (0,3):
    print(i)
    
    start2 = time.time()
    x = requests.post("http://0.0.0.0:8000/flan", json = myobj)
    end2 = time.time()
    print(x.text)

    sum_time+= (end2-start2)

avg_fast_api = sum_time/3
print("avg_fast_api: ",avg_fast_api)

```

### Expected behavior

As ucall is faster than fastapi, time required should be less in ucall. OR is it like when the task with high CPU utilization is there like transformers model, ucall and fastapi results are same???

Because when I checked for sum operation, at that time I got ucall faster than fastapi.

So question is, can I use ucall for faster perfomance, when large model like transformers are hosted?

### UCall version

0.5.4

### Operating System

Ubuntu 22.04.4 LTS

### Hardware architecture

x86

### Which interface are you using?

Official Python bindings

### Which implementation are you using?

io_uring

### Contact Details

mmk32001@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
The cost of running Flan-T5 inference is orders of magnitude higher, than handling network requests. You are practically measuring the variance between PyTorch calls.
