### ISSUE TITLE
Bug: Segmentation Fault when accessing server via client

### ISSUE THREAD

**Issue by rockerBOO** [unum-cloud/ujrpc#64]
### Describe the bug

Using ucall client to call a ucall server is causing the server to seg fault.

Attaching coredump info
[ucall-segfault-coredump.log](https://github.com/unum-cloud/ucall/files/11444465/ucall-segfault-coredump.log)

### Steps to reproduce

Server:

```python
# https://ashvardanian.com/posts/abusing-vector-search/#multi-index-lookups
from usearch import Index
from uform import get_model
from ucall.rich_posix import Server
from PIL import Image
import numpy as np

server = Server()

index_images = Index(ndim=256)
index_texts = Index(ndim=256)
index_coordinates = Index(metric='haversine')

model = get_model('unum-cloud/uform-vl-english')

@server
def recommend(text: str, image: Image, latitude: float, longitude: float) -> list[int]:
    vector_image = model.encode_image(model.preprocess_image(image)).numpy()
    vector_text = model.encode_text(model.preprocess_text(text)).numpy()
    vector_coordinate = np.array([latitude, longitude], dtype=np.float32)

    similar_images, _, _ = index_images.search(vector_image, 30)
    similar_texts, _, _ = index_texts.search(vector_text, 30)
    similar_coordinates, _, _ = index_coordinates.search(vector_coordinate, 100)

    # If a listing is physically close and matches text or image, it must be first.
    similar_contents = set(similar_images) + set(similar_texts)
    return [label for label in similar_coordinates if label in similar_contents]

server.run()
```

Client: 
```python
from ucall.client import Client
from PIL import Image
import geocoder
import json

client = Client()

text = "mountain top"
image = Image.open("/mnt/900/input/landscapes/processed-2/0f9wmnta7ik91+768x768.jpg")

[lat, long] = geocoder.ip('me').latlng

response = client.recommend(text=text, image=image, latitude=lat, longitude=long) 

print(response.json)
```

### Expected behavior

Expected to get a response back from the server, or an error to try to isolate the problem. Maybe my code is not accurate?

Thank you

### UCall version

0.4.0

### Operating System

archlinux

### Hardware architecture

x86

### Which interface are you using?

Official Python bindings

### Which implementation are you using?

POSIX

### Contact Details

hello@davelage.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks for the report and the dump! Is it supposed to be `from PIL import Image` or `from PIL.Image import Image`? First is a module, and last is a class: `<class 'PIL.Image.Image'>`.

**Comment by ashvardanian** [comment]
It may affect the type-inference inside `Server`, which causes later SEGFAULT in Torch. It may help to remove a few pieces to check which part fails.

**Comment by rockerBOO** [comment]
Yes setting the Image to the correct Image class seemed to have fixed it. Thank you

**Comment by ashvardanian** [comment]
@ishkhan42 Can we add an assert for unsupported types to prevent such problems in the future?
