### ISSUE TITLE
Bug: bool type error in `ucall.cli:cast`

### ISSUE THREAD

**Issue by Bing-su** [unum-cloud/ujrpc#81]
### Describe the bug

hello. I came here after looking at usearch on langchain and browsing the repository.

While looking at the code, I noticed a potential type error and wrote this issue.

https://github.com/unum-cloud/ucall/blob/bca04edaa8e2d238618e177965acac141e25fab8/src/ucall/cli.py#L31-L32

In Python, when you call bool on a non-empty string, its value is `True`, so the above function will always return `True`.

### Steps to reproduce

```py
>>> from ucall.cli import cast

>>> cast("True", None) is True
True
```

```py
>>> cast("False", None) is True
True
```

### Expected behavior

`cast("False", None)` should be `False`.

```py
        if value in ['True', 'False']:
            return value == 'True'
```

### UCall version

v0.5.1

### Operating System

Ubuntu 22.04

### Hardware architecture

x86

### Which interface are you using?

Official Python bindings

### Which implementation are you using?

posix

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hello, @Bing-su! Good catch! @ishkhan42, can you take a look at this?
