### ISSUE TITLE
Bug: reponse error: Out of memory

### ISSUE THREAD

**Issue by ybingHuang** [unum-cloud/ujrpc#89]
### Describe the bug

ucall server code:
from ucall.posix import Server

# from ucall.uring import Server on 5.19+

server = Server(
    port=8845,
    # ssl_pk='./examples/login/certs/main.key',
    # ssl_certs=[
    #   './examples/login/certs/srv.crt',
    #   './examples/login/certs/cas.pem']
)

class People:
    name: str
    gender: str
    age: int
    addr: str
    height: int
    weight: int
    hobbies: []

    def __init__(self, name, gender, age, addr, height, weight, hobbies):
        self.name = name
        self.gender = gender
        self.addr = addr
        self.age = age
        self.height = height
        self.weight = weight
        self.hobbies = hobbies

people = People('zhangsan', 'F', 18, 'cn', 185, 70, ['a', 'b', 'c'])

@server
def sum(a: int, b: int):
    return a + b

@server
def test_json():
    return people

server.run()

when i request the test_json method , response error message is Out of memory. 

### Steps to reproduce

![error](https://github.com/unum-cloud/ucall/assets/45745588/9485e9f3-8825-4240-84f6-0eb74f038d0f)

### Expected behavior

success data response

### UCall version

v0.5.1

### Operating System

4.19.90-25.5.v2101.ky10.aarch64

### Hardware architecture

Arm

### Which interface are you using?

Official Python bindings

### Which implementation are you using?

POSIX

### Contact Details

nikohuang0706@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hey, @ybingHuang! How large is the `people` array you are trying to return?

**Comment by ybingHuang** [comment]
> Hey, @ybingHuang! How large is the `people` array you are trying to return?
The method return only one people instance, not people array

**Comment by ashvardanian** [comment]
@ybingHuang, you have to return a native Pythonic object already serialized into something like a dictionary. The current v0.5.1 in PyPi should’t support arbitrary type objects.

**Comment by ybingHuang** [comment]
> @ybingHuang, you have to return a native Pythonic object already serialized into something like a dictionary. The current v0.5.1 in PyPi should’t support arbitrary type objects.

Well, in this case ,how can i return my people instance?

**Comment by ashvardanian** [comment]
Converting it to dictionary is the default way.
