### ISSUE TITLE
Feature: Python 3.12 support

### ISSUE THREAD

**Issue by mtasic85** [unum-cloud/ujrpc#92]
### Describe what you are looking for

Python 3.11 support is working great but, ecosystem moves to Python 3.12. Can you support Python 3.12 and publish new version?

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtasic85** [comment]
Any update on this one?

**Comment by ashvardanian** [comment]
There seems to be an issue with MacOS CI - investigating 🤷‍♂️

**Comment by ashvardanian** [comment]
Seems like the new parallel CI I'm using in StringZilla worked here as well, and a refreshed package must be approaching PyPi 🤗 @mtasic85 please let me know if it works as expected!
